version: '2'
services:
    conductiontests-app:
        image: conductiontests
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://conductiontests-postgresql:5432/ConductionTests
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    conductiontests-postgresql:
        extends:
            file: postgresql.yml
            service: conductiontests-postgresql
